//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coinoneAlarm.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("coinoneAlarm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap coin_logo_bch {
            get {
                object obj = ResourceManager.GetObject("coin_logo_bch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap coin_logo_btc {
            get {
                object obj = ResourceManager.GetObject("coin_logo_btc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap coin_logo_btg {
            get {
                object obj = ResourceManager.GetObject("coin_logo_btg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap coin_logo_etc {
            get {
                object obj = ResourceManager.GetObject("coin_logo_etc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap coin_logo_eth {
            get {
                object obj = ResourceManager.GetObject("coin_logo_eth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap coin_logo_iota {
            get {
                object obj = ResourceManager.GetObject("coin_logo_iota", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap coin_logo_ltc {
            get {
                object obj = ResourceManager.GetObject("coin_logo_ltc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap coin_logo_qtum {
            get {
                object obj = ResourceManager.GetObject("coin_logo_qtum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap coin_logo_xrp {
            get {
                object obj = ResourceManager.GetObject("coin_logo_xrp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon coinone_icon {
            get {
                object obj = ResourceManager.GetObject("coinone_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_auth {
            get {
                object obj = ResourceManager.GetObject("icon_auth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_buy {
            get {
                object obj = ResourceManager.GetObject("icon_buy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_notice_off {
            get {
                object obj = ResourceManager.GetObject("icon_notice_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_notice_on {
            get {
                object obj = ResourceManager.GetObject("icon_notice_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   비트코인 캐시(BCH)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ITEM_BCH {
            get {
                return ResourceManager.GetString("ITEM_BCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비트코인(BTC)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ITEM_BTC {
            get {
                return ResourceManager.GetString("ITEM_BTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비트코인 골드(BTG)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ITEM_BTG {
            get {
                return ResourceManager.GetString("ITEM_BTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이더리움 클래식(ETC)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ITEM_ETC {
            get {
                return ResourceManager.GetString("ITEM_ETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이더리움(ETH)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ITEM_ETH {
            get {
                return ResourceManager.GetString("ITEM_ETH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이오타(IOTA)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ITEM_IOTA {
            get {
                return ResourceManager.GetString("ITEM_IOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라이트코인(LTC)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ITEM_LTC {
            get {
                return ResourceManager.GetString("ITEM_LTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   퀀텀(QTUM)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ITEM_QTUM {
            get {
                return ResourceManager.GetString("ITEM_QTUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리플(XRP)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ITEM_XRP {
            get {
                return ResourceManager.GetString("ITEM_XRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap line_horizon {
            get {
                object obj = ResourceManager.GetObject("line_horizon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_CLOSE {
            get {
                return ResourceManager.GetString("MENU_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_EXIT {
            get {
                return ResourceManager.GetString("MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_OPEN {
            get {
                return ResourceManager.GetString("MENU_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_SETTINGS {
            get {
                return ResourceManager.GetString("MENU_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}의 가격이 알림가에 도달하였습니다.
        ///알림가 : {1} KRW
        ///현재가 : {2} KRW과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MESSAGE_NOTICE_COIN_PRICE {
            get {
                return ResourceManager.GetString("MESSAGE_NOTICE_COIN_PRICE", resourceCulture);
            }
        }
    }
}
